package main

// /compact: trade the conversation for a summary of it. The summary is
// generated by the current target with no tools attached, seeded into a fresh
// session, and the old session stays on disk untouched — compaction is a new
// log that starts informed, never an edit to the record (§12's append-only
// posture). The optional argument steers the summary: /compact focus on the
// migration plan.

import (
	"context"
	"fmt"
	"strconv"
	"strings"
	"time"

	tea "github.com/charmbracelet/bubbletea"

	"github.com/cj-vana/switchboard/internal/config"
	"github.com/cj-vana/switchboard/internal/prefix"
	"github.com/cj-vana/switchboard/internal/provider"
)

const compactSystem = `You are summarizing a coding session so it can continue in a fresh context window. Write for the model that continues the work, not for a human. Capture: the task and its current state; what was tried and what failed, so nothing is repeated; decisions made and their reasons; file paths touched and what changed in each; exact commands, errors, and identifiers worth keeping; and what remains to be done, most immediate first. Plain text, no preamble, no headers about being a summary. Length proportional to what actually happened.`

const compactUsage = "usage: /compact [guidance], /compact preview, /compact auto [on|off], or /compact at <50–95>"

// compactSeedHead opens every compacted session's seed message. The session
// listings match on it to label such a session by its summary's first words
// rather than by a preamble every compacted session shares.
const compactSeedHead = "This session continues an earlier one ("

func cmdCompact(m *tuiModel, args string) tea.Cmd {
	if cmd, handled := compactSettings(m, args); handled {
		return cmd
	}
	return compactCmd(m, strings.TrimSpace(args), false)
}

// summarizerFor resolves which model writes the summary. The slots table
// wins — a summarizer slot is the statement that compaction quality should
// not depend on which rung happens to be active, and a session riding a
// small local model is exactly when that matters. Absent a binding, the
// current tier does its own summarizing, which is what it always did.
func summarizerFor(app *tuiApp) (config.Tier, bool, error) {
	ref, bound := app.config.Slots["summarizer"]
	if !bound {
		return app.tier, false, nil
	}
	if t, found := app.config.Tier(ref); found {
		return t, true, nil
	}
	target, err := config.ParseTarget(ref, "", "")
	if err != nil {
		return config.Tier{}, true, fmt.Errorf("the [slots] summarizer entry does not parse: %w", err)
	}
	return config.Tier{ID: "-summarizer", Label: "summarizer", Target: target}, true, nil
}

// compactCmd is the compaction itself; auto marks the threshold-triggered
// path, whose failure handling differs in one place: a summarizer slot that
// cannot be reached fails a manual /compact outright, but the automatic path
// falls back to the current tier and says so, because it fires precisely
// when the session is about to hit the wall and stopping there would deliver
// the failure compaction exists to prevent.
func compactCmd(m *tuiModel, instructions string, auto bool) tea.Cmd {
	state := m.app.loop.Session.State()
	if len(state.Messages) == 0 {
		return noticeCmd("", "nothing to compact yet")
	}

	summarizer, fromSlot, err := summarizerFor(m.app)
	if err != nil {
		return noticeCmd("error", err.Error())
	}

	line := "compacting: summarizing " + itoa(len(state.Messages)) + " messages on " + string(summarizer.Target.ID())
	if fromSlot {
		line += " (the summarizer slot)"
	}
	m.addInfo(line + "…")

	app := m.app
	return func() tea.Msg {
		ctx, cancel := context.WithTimeout(context.Background(), 5*time.Minute)
		defer cancel()

		client, target := app.loop.Provider, app.tier.Target
		if fromSlot {
			probed, slotClient, perr := app.providers.probeTier(ctx, summarizer)
			switch {
			case perr == nil:
				client, target = slotClient, probed.Target
			case auto:
				app.p.Send(noticeMsg{level: "warn", text: "summarizer slot " + string(summarizer.Target.ID()) +
					" is unreachable (" + perr.Error() + "); compacting with the current tier instead"})
			default:
				return noticeMsg{level: "error", text: "summarizer slot " + string(summarizer.Target.ID()) +
					" is unreachable, session unchanged: " + perr.Error()}
			}
		}

		summary, err := summarize(ctx, client, target, state.Messages, instructions)
		if err != nil {
			return noticeMsg{level: "error", text: "compact failed, session unchanged: " + err.Error()}
		}

		sess, err := app.store.Create(app.workspace, app.tier.Target.ID(), app.catalog.Revision)
		if err != nil {
			return noticeMsg{level: "error", text: "compact failed, session unchanged: " + err.Error()}
		}
		seed := compactSeedHead + state.ID + "). What follows is a summary of that conversation; treat it as established context.\n\n" + summary
		// The acknowledgment keeps the log strictly alternating, which every
		// adapter renders correctly; a seed followed directly by the user's
		// next prompt would put two user messages back to back.
		if err := sess.AppendMessage(provider.UserText(seed)); err == nil {
			err = sess.AppendMessage(provider.Message{
				Role:    provider.RoleAssistant,
				Content: []provider.Block{provider.Text{Text: "Understood. Continuing from there."}},
			})
		}
		if err != nil {
			sess.Close()
			return noticeMsg{level: "error", text: "compact failed, session unchanged: " + err.Error()}
		}
		return sessionSwapMsg{sess: sess, tier: app.tier, client: app.loop.Provider, fresh: false}
	}
}

// compactSettings is /compact auto and /compact at: the automatic-compaction
// posture, set from inside the TUI and persisted like every other setting.
// Anything else is guidance for a manual compaction and is not handled here.
func compactSettings(m *tuiModel, args string) (tea.Cmd, bool) {
	what, value, _ := strings.Cut(strings.TrimSpace(args), " ")
	value = strings.TrimSpace(value)
	cfg := m.app.config
	switch what {
	case "preview":
		// What compaction would do, before it does it: the conversation is
		// what a summary replaces, the frozen zone rides into the fresh
		// context unchanged, and the numbers are the estimator's own floor,
		// said as estimates. The decision this informs is compact-or-fork,
		// and it deserves the same visibility every other decision gets.
		state := m.app.loop.Session.State()
		if len(state.Messages) == 0 {
			return noticeCmd("", "nothing to compact yet"), true
		}
		conv := prefix.RequestTokens(provider.Request{Messages: state.Messages})
		sys := prefix.RequestTokens(provider.Request{System: m.app.loop.System})
		tools := prefix.RequestTokens(provider.Request{Tools: m.app.loop.Tools.Definitions()})
		summarizer, fromSlot, err := summarizerFor(m.app)
		if err != nil {
			return noticeCmd("error", err.Error()), true
		}
		who := "the active rung"
		if fromSlot {
			who = "the summarizer slot (" + summarizer.ID + ")"
		}
		var b strings.Builder
		fmt.Fprintf(&b, "compaction would summarize %d messages, ~%s conversation tokens, into a fresh context\n",
			len(state.Messages), compact(conv))
		fmt.Fprintf(&b, "system and tools (~%s) ride unchanged; %s writes the summary\n", compact(sys+tools), who)
		b.WriteString("the alternative is /fork, which keeps the full conversation and the warm prefix; /compact runs it")
		m.addInfo(b.String())
		return nil, true
	case "auto":
		switch value {
		case "":
			state := "on"
			if !cfg.CompactAuto {
				state = "off"
			}
			return noticeCmd("", "auto-compaction is "+state+", at "+itoa(compactThreshold(cfg))+"% of the window"), true
		case "on", "off":
			cfg.CompactAuto = value == "on"
			if err := cfg.Save(); err != nil {
				return noticeCmd("error", "saving the setting failed: "+err.Error()), true
			}
			return noticeCmd("", "auto-compaction is now "+value), true
		default:
			return noticeCmd("error", compactUsage), true
		}
	case "at":
		n, err := strconv.Atoi(value)
		if err != nil || n < 50 || n > 95 {
			return noticeCmd("error", compactUsage), true
		}
		cfg.CompactAtPercent = n
		if err := cfg.Save(); err != nil {
			return noticeCmd("error", "saving the threshold failed: "+err.Error()), true
		}
		return noticeCmd("", "auto-compaction now triggers at "+value+"% of the window"), true
	}
	return nil, false
}

func compactThreshold(cfg *config.Config) int {
	if cfg.CompactAtPercent == 0 {
		return 85
	}
	return cfg.CompactAtPercent
}

// summarize is a one-shot request outside the loop: no tools, no session
// append, just the conversation and an instruction to compress it.
func summarize(ctx context.Context, client provider.Provider, target provider.RouteTarget, messages []provider.Message, instructions string) (string, error) {
	ask := "Summarize the conversation so far, per your instructions."
	if instructions != "" {
		ask += " Additional guidance from the user: " + instructions
	}
	req := provider.Request{
		System:   []provider.Block{provider.Text{Text: compactSystem}},
		Messages: append(append([]provider.Message{}, messages...), provider.UserText(ask)),
	}

	stream, err := client.Stream(ctx, target, req)
	if err != nil {
		return "", err
	}
	defer stream.Close()

	var b strings.Builder
	for {
		ev, err := stream.Next()
		if err != nil {
			return "", err
		}
		switch ev.Type {
		case provider.EventTextDelta:
			b.WriteString(ev.Text)
		case provider.EventDone:
			if s := strings.TrimSpace(b.String()); s != "" {
				return s, nil
			}
			return "", fmt.Errorf("the model returned an empty summary")
		}
	}
}
