package main

// /compact: trade the conversation for a summary of it. The summary is
// generated by the current target with no tools attached, seeded into a fresh
// session, and the old session stays on disk untouched — compaction is a new
// log that starts informed, never an edit to the record (§12's append-only
// posture). The optional argument steers the summary: /compact focus on the
// migration plan.

import (
	"context"
	"fmt"
	"strconv"
	"strings"
	"time"

	tea "github.com/charmbracelet/bubbletea"

	"github.com/cj-vana/switchboard/internal/config"
	"github.com/cj-vana/switchboard/internal/provider"
)

const compactSystem = `You are summarizing a coding session so it can continue in a fresh context window. Write for the model that continues the work, not for a human. Capture: the task and its current state; what was tried and what failed, so nothing is repeated; decisions made and their reasons; file paths touched and what changed in each; exact commands, errors, and identifiers worth keeping; and what remains to be done, most immediate first. Plain text, no preamble, no headers about being a summary. Length proportional to what actually happened.`

const compactUsage = "usage: /compact [guidance], /compact auto [on|off], or /compact at <50–95>"

func cmdCompact(m *tuiModel, args string) tea.Cmd {
	if cmd, handled := compactSettings(m, args); handled {
		return cmd
	}

	state := m.app.loop.Session.State()
	if len(state.Messages) == 0 {
		return noticeCmd("", "nothing to compact yet")
	}

	m.addInfo("compacting: summarizing " + itoa(len(state.Messages)) + " messages on " + string(m.app.tier.Target.ID()) + "…")

	app := m.app
	instructions := strings.TrimSpace(args)
	return func() tea.Msg {
		ctx, cancel := context.WithTimeout(context.Background(), 5*time.Minute)
		defer cancel()

		summary, err := summarize(ctx, app.loop.Provider, app.tier.Target, state.Messages, instructions)
		if err != nil {
			return noticeMsg{level: "error", text: "compact failed, session unchanged: " + err.Error()}
		}

		sess, err := app.store.Create(app.workspace, app.tier.Target.ID(), app.catalog.Revision)
		if err != nil {
			return noticeMsg{level: "error", text: "compact failed, session unchanged: " + err.Error()}
		}
		seed := "This session continues an earlier one (" + state.ID + "). What follows is a summary of that conversation; treat it as established context.\n\n" + summary
		// The acknowledgment keeps the log strictly alternating, which every
		// adapter renders correctly; a seed followed directly by the user's
		// next prompt would put two user messages back to back.
		if err := sess.AppendMessage(provider.UserText(seed)); err == nil {
			err = sess.AppendMessage(provider.Message{
				Role:    provider.RoleAssistant,
				Content: []provider.Block{provider.Text{Text: "Understood. Continuing from there."}},
			})
		}
		if err != nil {
			sess.Close()
			return noticeMsg{level: "error", text: "compact failed, session unchanged: " + err.Error()}
		}
		return sessionSwapMsg{sess: sess, tier: app.tier, client: app.loop.Provider, fresh: false}
	}
}

// compactSettings is /compact auto and /compact at: the automatic-compaction
// posture, set from inside the TUI and persisted like every other setting.
// Anything else is guidance for a manual compaction and is not handled here.
func compactSettings(m *tuiModel, args string) (tea.Cmd, bool) {
	what, value, _ := strings.Cut(strings.TrimSpace(args), " ")
	value = strings.TrimSpace(value)
	cfg := m.app.config
	switch what {
	case "auto":
		switch value {
		case "":
			state := "on"
			if !cfg.CompactAuto {
				state = "off"
			}
			return noticeCmd("", "auto-compaction is "+state+", at "+itoa(compactThreshold(cfg))+"% of the window"), true
		case "on", "off":
			cfg.CompactAuto = value == "on"
			if err := cfg.Save(); err != nil {
				return noticeCmd("error", "saving the setting failed: "+err.Error()), true
			}
			return noticeCmd("", "auto-compaction is now "+value), true
		default:
			return noticeCmd("error", compactUsage), true
		}
	case "at":
		n, err := strconv.Atoi(value)
		if err != nil || n < 50 || n > 95 {
			return noticeCmd("error", compactUsage), true
		}
		cfg.CompactAtPercent = n
		if err := cfg.Save(); err != nil {
			return noticeCmd("error", "saving the threshold failed: "+err.Error()), true
		}
		return noticeCmd("", "auto-compaction now triggers at "+value+"% of the window"), true
	}
	return nil, false
}

func compactThreshold(cfg *config.Config) int {
	if cfg.CompactAtPercent == 0 {
		return 85
	}
	return cfg.CompactAtPercent
}

// summarize is a one-shot request outside the loop: no tools, no session
// append, just the conversation and an instruction to compress it.
func summarize(ctx context.Context, client provider.Provider, target provider.RouteTarget, messages []provider.Message, instructions string) (string, error) {
	ask := "Summarize the conversation so far, per your instructions."
	if instructions != "" {
		ask += " Additional guidance from the user: " + instructions
	}
	req := provider.Request{
		System:   []provider.Block{provider.Text{Text: compactSystem}},
		Messages: append(append([]provider.Message{}, messages...), provider.UserText(ask)),
	}

	stream, err := client.Stream(ctx, target, req)
	if err != nil {
		return "", err
	}
	defer stream.Close()

	var b strings.Builder
	for {
		ev, err := stream.Next()
		if err != nil {
			return "", err
		}
		switch ev.Type {
		case provider.EventTextDelta:
			b.WriteString(ev.Text)
		case provider.EventDone:
			if s := strings.TrimSpace(b.String()); s != "" {
				return s, nil
			}
			return "", fmt.Errorf("the model returned an empty summary")
		}
	}
}
